# Generated by Django 4.2.1 on 2025-02-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_expenses_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='bank',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='investement',
            field=models.BooleanField(default=False),
        ),
    ]
