# Generated by Django 4.2.1 on 2025-02-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_expenses_bank_expenses_category_expenses_investement'),
    ]

    operations = [
        migrations.CreateModel(
            name='totals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_money', models.IntegerField()),
                ('spent_money', models.IntegerField()),
            ],
        ),
    ]
