# Generated by Django 4.2.1 on 2025-02-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_totals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='investement',
            new_name='investment',
        ),
    ]
