# Generated by Django 4.2.1 on 2025-08-08 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_expenses_user_totals_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='bank',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='totals',
            name='invested_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='totals',
            name='spent_money',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PersonalEmis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_name', models.CharField(default='Your Emi Name', max_length=1000)),
                ('emi_total_amount', models.IntegerField(default=0)),
                ('emi_monthly_deduction_date', models.CharField(max_length=100)),
                ('emi_monthly_installement_amount', models.IntegerField(default=0)),
                ('emi_total_months_duration', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_emis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name', models.CharField(default='Your Bill name ', max_length=9999)),
                ('date_of_expenditure', models.CharField(max_length=100000)),
                ('bill_pdf', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ImportantBills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
